### ISSUE TITLE
Trajectories not properly compressed

### ISSUE THREAD

**Issue by feixieliz** [TheAgentCompany/experiments#2]
Decompressing the trajectories using
```
with gzip.open(gz_path, 'rt', encoding='UTF-8') as f_in:
    data = json.load(f_in)
```
returned error `gzip.BadGzipFile: Not a gzipped file (b've')` for 696 ( = 175*4 -4) trajectories. These trajectories come from the following 4 models:
- gpt-4o-2024-08-06
- llama-3.1-405b
- qwen2-72b
- sonnet-20241022

In each of these 4 models only one trajectory `traj_sde-report-unit-test-coverage-to-plane-image.json.gz` can be decompressed.

**Comment by yufansong** [comment]
@li-boxuan can you help check this?

**Comment by li-boxuan** [comment]
I can use my Macbook's Archive Utility to uncompress those files though.

**Comment by li-boxuan** [comment]
Probably the way I compress is not following standard gzip format. Will look into that later today.

**Comment by feixieliz** [comment]
Maybe those files were compressed successfully locally but not uploaded to the GitHub properly. 
Here is the screenshot if I use my Macbook's Archive Utility to uncompress after `git clone`:
<img width="382" alt="Screenshot 2024-12-21" src="https://github.com/user-attachments/assets/9bbb1c86-eca9-4c75-b070-05f85018666c" />

Here is the screenshot if I click **view raw** directly on GitHub:
<img width="1451" alt="Screenshot 2024-12-21" src="https://github.com/user-attachments/assets/96eeeab0-c41d-4c6d-9219-b332b6954ef4" />

**Comment by li-boxuan** [comment]
Thanks for reporting @feixieliz ! Can you please try again? You need to use 

```
>>> with gzip.open(gz_path, 'rb') as f_in:
...     data = json.load(f_in)
```

to decompress the file.

**Comment by feixieliz** [comment]
@li-boxuan Works now, thanks!

**Comment by feixieliz** [comment]
Closing the issue.
